create database busyqacrm6;
use busyqacrm6;
select * from positions; 
select * from users;
select * from user_position;

INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_USER','TEAM_SALES');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_ADMIN','TEAM_SALES');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_PM','TEAM_SALES');

INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_USER','TEAM_ACCOUNTS');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_ADMIN','TEAM_ACCOUNTS');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_PM','TEAM_ACCOUNTS');

INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME)  VALUES('ROLE_USER','TEAM_ADMIN');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_ADMIN','TEAM_ADMIN');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_PM','TEAM_ADMIN');

INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_USER','TEAM_UNASSIGNED');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_PM','TEAM_UNASSIGNED');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_ADMIN','TEAM_UNASSIGNED');

INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_CLIENT','TEAM_LEAD');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_CLIENT','TEAM_STUDENT');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_CLIENT','TEAM_INTERN');
INSERT INTO POSITIONS (ROLE_NAME, TEAM_NAME) VALUES('ROLE_CLIENT','TEAM_ALUMNI');





-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_SALES');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_SALES');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_ACCOUNTS');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_ACCOUNTS');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_ADMIN');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_ADMIN');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_UNASSIGNED');










-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_SALES');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_SALES');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_ACCOUNTS');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_ACCOUNTS');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_ADMIN');
-- INSERT INTO postions(name) VALUES('ROLE_ADMIN,TEAM_ADMIN');
-- INSERT INTO postions(name) VALUES('ROLE_USER,TEAM_UNASSIGNED');




